export const Projects = [
  {
    title: `Simon Game`,
    image: "/projects/simon.png",
    des: `The original Simon Game created in Next.js App`,
    link: "https://simon-game-lilac-delta.vercel.app",
    github: "https://github.com/Hmalhotra004/simon-game",
    tech: ["Next.js", "Typescript", "SCSS", "Framer Motion"],
  },
  // {
  //   title: `Project Manager`,
  //   image: "/projects/simon.png",
  //   des: `Its a Project Manager`,
  //   link: "https://project-manager-omega-blue.vercel.app",
  //   github: "https://github.com/Hmalhotra004/project-manager",
  //   tech: ["Next.js", "Typescript", "TailwindCSS","Redux Toolkit", "Firebase", "Framer Motion"],
  // },
  {
    title: `Quizzler`,
    image: "/projects/quiz.png",
    des: `A Quizz app about everything using an trivia api`,
    link: "https://quizzler-three.vercel.app",
    github: "https://github.com/Hmalhotra004/quizzler",
    tech: ["Next.js", "Typescript", "SCSS", "Axios"],
  },
  {
    title: `NMTechFest'24 Website`,
    image: "/projects/tf.png",
    des: `Official website of NMTechfest'24`,
    link: "https://techfest-website-24.vercel.app",
    github: "https://github.com/Hmalhotra004/techfest-website-24",
    tech: ["Next.js", "Typescript", "SCSS", "Framer Motion"],
  },
  {
    title: `Tic-Tac-Toe`,
    image: "/projects/tic.png",
    des: `A Tic-Tac-Toe Game`,
    link: "https://tic-tac-toe-three-peach.vercel.app",
    github: "https://github.com/HardikMalhotra/Tic-Tac-Toe",
    tech: ["HTML", "CSS", "Javascript"],
  },
  // {
  //   title: `Mini-Projects`,
  //   image: "/projects/mp.png",
  //   des: `Various small projects build with vanilla javascript`,
  //   link: "https://mini-projects-sigma.vercel.app/",
  //   github: "https://github.com/Hmalhotra004/Mini-Projects",
  //   tech: ["HTML", "CSS", "Javascript"],
  // },
];
