export default function Home() {
  return (
    <section className="overflow-x-hidden">
      <div className="absolute top-0 z-[-2] h-screen w-screen bg-neutral-950 bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.3),rgba(255,255,255,0))]"></div>
      <h1>Home Page</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam alias aperiam quod facere dolores necessitatibus saepe voluptate, perspiciatis nemo beatae ducimus sunt dolorum fuga, nam, porro vero veritatis cumque dolor. Accusantium eligendi, inventore quas quo incidunt blanditiis officia pariatur est unde, eaque deserunt accusamus quaerat tempora ipsa reprehenderit quasi corporis! Saepe eos ea, libero neque id ducimus doloribus incidunt cupiditate. Architecto dolore, voluptatum eaque sunt laudantium, accusamus sed libero dolorum excepturi aliquam iste dolor dicta maiores minus hic. Qui illum ex aperiam est quo incidunt eius praesentium accusantium doloribus expedita! Eveniet, corporis assumenda. Illo velit modi quis nisi. A, ipsam. Repellendus voluptates perspiciatis vitae iste modi aperiam reiciendis! Esse ipsa perspiciatis dolorum, perferendis obcaecati explicabo provident unde optio nam labore? Recusandae non vero aperiam deserunt veniam reiciendis totam ipsa vel esse corrupti dolorum praesentium maxime modi unde debitis inventore, laborum nam optio dolorem perferendis quisquam facilis expedita perspiciatis placeat! Minima. Deserunt architecto ut odio vero sapiente minus voluptates, ducimus distinctio sunt eaque unde vitae quod adipisci quas. Hic, ad, aperiam, cumque qui ducimus inventore explicabo atque blanditiis aspernatur sequi doloremque. Est molestias possimus, eveniet eius quis aperiam voluptatibus necessitatibus vitae a laudantium deserunt iste, repellat et commodi obcaecati, atque facilis illum voluptas? Facilis quis rem cumque ullam impedit tempora rerum. Alias repellat possimus quaerat voluptate nulla consectetur consequatur, hic magnam sint similique animi quisquam ab dolorem harum sed dolor repudiandae tempore? Vero sint sed esse iusto in, natus voluptatibus at? Harum delectus, minima pariatur numquam illum sunt tenetur reprehenderit nisi sapiente illo est commodi? Expedita minus nesciunt quasi officia. Dicta ex perspiciatis neque rem expedita odit cum minima laboriosam assumenda. Cumque quisquam odio eaque voluptatibus repellendus ex ab mollitia voluptatem odit necessitatibus? Illum debitis atque cum, praesentium qui perferendis quisquam, nostrum ipsam aliquam eligendi officiis porro omnis. Porro, numquam dolorum.</p>
      {/* <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur omnis et saepe. Eligendi quo nostrum consequuntur porro nisi voluptates delectus dolore placeat quae quaerat? Soluta quod consectetur iusto illo vel. Laborum earum nulla a numquam. Deserunt repellendus atque vel magnam voluptatum asperiores nulla architecto amet pariatur quam quasi nesciunt soluta id minima, at odio neque dignissimos cumque quia exercitationem voluptates. Quibusdam, accusantium voluptatum dignissimos magni enim nisi, itaque eligendi tenetur quam ducimus sapiente, architecto sunt debitis consectetur. Dicta quaerat veniam atque cum minima numquam, eveniet praesentium dolorum voluptas blanditiis. Ab. Labore cumque eaque ducimus excepturi maiores maxime porro nesciunt eos quod expedita temporibus vel mollitia, ipsam dolorem ut consectetur corporis suscipit sed voluptatibus illum ratione veritatis quia! Laudantium, fuga dolores? Perferendis iste error sit, repudiandae illo aut nobis a, minima, facere aliquam ea odit magni eius expedita explicabo. Perspiciatis, placeat vero! Doloribus quis sapiente eius minus atque totam maxime. Doloribus. At amet quod praesentium a impedit adipisci id delectus voluptatem totam minima facilis commodi obcaecati harum quaerat odio dicta doloremque mollitia ut ipsam atque, esse rem fugit quibusdam. Ipsam, necessitatibus. Error optio accusantium obcaecati. Alias vero nostrum in maiores molestiae inventore numquam aperiam eum provident amet. Repellendus, corporis tempore? Pariatur illum aliquid voluptatibus quod praesentium neque unde, modi ipsa nulla! Quod a perspiciatis voluptatibus consequatur unde amet minima cumque asperiores iure, reprehenderit ipsa? Deserunt, distinctio quidem porro incidunt nihil laboriosam, tenetur reprehenderit libero quaerat soluta architecto nesciunt voluptas. Maiores, iusto. Error impedit vitae iure aliquam corrupti ipsam, recusandae quod facilis ipsa debitis ut, voluptas minus voluptatibus nemo deserunt. Nobis, amet aperiam! Iusto magni expedita reiciendis amet explicabo, quibusdam deserunt! Non? Porro veritatis ea minus. Voluptas dicta deserunt, velit ut quas omnis nam at commodi itaque consequuntur neque debitis corrupti obcaecati tempore quo, officiis asperiores distinctio, illum aliquam. Expedita, quidem repudiandae!</p> */}
    </section>
  );
}
